# Generated by Django 4.1.3 on 2023-03-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('hospital_address', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('cobra_antidote', models.BooleanField(default=False)),
                ('python_antidote', models.BooleanField(default=False)),
                ('russel_antidote', models.BooleanField(default=False)),
            ],
        ),
    ]
